# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedVocabVariables',
            fields=[
                ('request_id', models.CharField(max_length=125, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('glossary_dict', models.TextField(blank=True, null=True)),
                ('initial_select_table', models.TextField(blank=True, null=True)),
                ('select_table', models.TextField(blank=True, null=True)),
                ('quiz_select_table', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('school', models.CharField(blank=True, max_length=100)),
                ('invitation', models.CharField(blank=True, max_length=30, null=True)),
                ('invitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='ums.Profile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='analyzedvocabvariables',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_vocab_variables', to='ums.Profile'),
        ),
    ]
