# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0002_analyzedvocabvariables'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedvocabvariables',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyzedvocabvariables',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_vocab_variables', to='ums.Profile'),
        ),
    ]
