# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lexicon', '0001_initial'),
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='SessionVariables',
            fields=[
                ('request_id', models.CharField(max_length=125, primary_key=True, serialize=False)),
                ('glossary_dict', models.TextField(blank=True, null=True)),
                ('select_table', models.TextField(blank=True, null=True)),
                ('quiz_select_table', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_variables', to='ums.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TempFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('upload', models.FileField(upload_to='temp/%Y/%m/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_files', to='ums.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='EntryPointerQuery',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('lexicon.entrypointer',),
        ),
    ]
