# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gargoyle', '0002_sessionvariables_saved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionvariables',
            name='initial_select_table',
            field=models.TextField(blank=True, null=True),
        ),
    ]
