# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gargoyle', '0003_sessionvariables_initial_select_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionvariables',
            name='saved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
