# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gargoyle', '0004_auto_20170509_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionvariables',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
