# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gargoyle', '0005_sessionvariables_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionvariables',
            name='progress',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
