# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0004_analyzedvocabvariables_show'),
        ('gargoyle', '0006_sessionvariables_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_cutoff', models.FloatField(default=4.3)),
                ('diff_cutoff', models.FloatField(default=6)),
                ('learner_pref', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('webster_pref', models.IntegerField(choices=[(1, 1), (2, 2)], default=2)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_preference', to='ums.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='sessionvariables',
            name='progress',
            field=models.FloatField(blank=True, default=3, null=True),
        ),
    ]
