# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 03:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gargoyle', '0008_auto_20170519_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabpreference',
            name='diff_cutoff',
            field=models.FloatField(default=6, validators=[django.core.validators.MinValueValidator(-2.0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='vocabpreference',
            name='show_cutoff',
            field=models.FloatField(default=4.3, validators=[django.core.validators.MinValueValidator(-2.0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
