# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabvariables',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mining_vocab_variables', to='ums.Profile'),
        ),
    ]
