# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpointer',
            name='lemmas',
            field=models.ManyToManyField(blank=True, related_name='_wordpointer_lemmas_+', to='lexicon.WordPointer'),
        ),
    ]
