# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0002_wordpointer_lemmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpointer',
            name='lemmas',
            field=models.ManyToManyField(blank=True, related_name='derivations', to='lexicon.WordPointer'),
        ),
    ]
