# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0003_auto_20170422_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngrams',
            fields=[
                ('word', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('raw_freq', models.DecimalField(decimal_places=13, max_digits=15, null=True)),
                ('word_pointer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngrams', to='lexicon.WordPointer')),
            ],
        ),
    ]
