# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0004_ngrams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngrams',
            name='raw_freq',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
    ]
