webster_pos_list = [u'',
 u'adjectivecombiningform',
 u'suffix',
 u'pronoun',
 u'pronoun,pluralinconstruction',
 u'nounpluralbutusuallysingularin',
 u'pronoun,sometimespluralinconst',
 u'adjective',
 u'preposition',
 u'prefix',
 u'biographicalname',
 u'adjectivesuffix',
 u'abbreviation',
 u'nounpluralsuffix',
 u'servicemark',
 u'nounplural',
 u'nounsuffixorpronounsuffix',
 u'geographicalname',
 u'adjectiveoradverbcombiningform',
 u'teaserentry',
 u'adverb',
 u'nounoradjective',
 u'trademark',
 u'adverbsuffix',
 u'nounsingularbutsingularorplura',
 u'nouncombiningform',
 u'nouncombformoradjectivecombfor',
 u'definitearticle',
 u'verbsuffix',
 u'foreignterm',
 u'nounpluralbutsingularorplurali',
 u'verbimperative',
 u'combiningform',
 u'symbol',
 u'pronounoradjective',
 u'nounpluralbutsingularinconstru',
 u'verb',
 u'conjunction',
 u'adjectiveornoun',
 u'indefinitearticle',
 u'verbalauxiliary',
 u'noun',
 u'pronoun,singularorpluralincons',
 u'nounsuffix',
 u'adjectiveoradverb',
 u'pronounplural',
 u'interjection',
 u'adverboradjective',
 u'adverbcombiningform',
 u'inter',
 u'nounortransitiveverb']
 
pos_ignore_list = [
 u'adjectivecombiningform',
 u'suffix',
 u'pronoun',
 u'preposition',
 u'prefix',
 u'biographicalname',
 u'adjectivesuffix',
 u'abbreviation',
 u'nounpluralsuffix',
 u'servicemark',
 u'nounsuffixorpronounsuffix',
 u'geographicalname',
 u'adjectiveoradverbcombiningform',
 u'trademark',
 u'nouncombiningform',
 u'nouncombformoradjectivecombfor',
 u'verbsuffix',
 u'verbalauxiliary',
 u'symbol',
 u'pronounoradjective',
 u'interjection',
 u'adverbcombiningform',
 u'conjunction'
]
  
coca_pos_list =[
 u'vmk', u'cc', u'jjt', u'vm', u'vbn', u'ii', u'ge', u'at', u'vv', u'cs', u'rrt', u'rrr', u'vd0', u'pp', u'jjr', u'rr', u'vh0', u'to', u'vb0', u'at1', u'pn', u'vvgk', u'uh', u'vvz', u'dd', u'db', u'da', u'vvn', u'vbdz', u'appge', u'jj', u'vbz', u'vvg', u'vbdr', u'vvd', u'nn2', u'nn1', u'md', u'mf', u'vbg', u'mc', u'vhz', u'vdz', u'xx', u'vbm', u'vbr', u'vhn', u'vv0', u'vdd', u'vdg', u'vhd', u'vhg', u'vdn', u'ex']
 
coca_pos_dict ={
 'vv':'verb',
 'vvgk':'verb',
 'vvz':'verb',
 'vvn':'verb',
 'vvg':'verb',
 'vvd':'verb',
 'vv0':'verb',
 'rr':'adverb',
 'rrt':'adverb',
 'rrr':'adverb',
 'jj':'adjective',
 'jjt':'adjective',    
 'jjr':'adjective',
 'nn2':'noun',
 'nn1':'noun',
}
 
pos_freq_initial = {
     'verb':0,
     'noun':0,
     'adjective':0,
     'adverb':0
 }