# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ums', '0003_auto_20170509_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ip_addr', models.CharField(max_length=50)),
                ('request_type', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_data', to='ums.Profile')),
            ],
        ),
    ]
