# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_value', models.IntegerField(default=100)),
                ('expiration_date', models.IntegerField(default=100)),
                ('repeat', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, default='New Customer', max_length=100)),
                ('remains', models.IntegerField(default=100)),
                ('repeat_remain', models.IntegerField(default=0)),
                ('expired', models.BooleanField(default=False)),
                ('activation_date', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocrbundles', to='ums.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OcrBundleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_value', models.IntegerField(default=100)),
                ('expiration_date', models.IntegerField(default=100)),
                ('repeat', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, default='New Customer', max_length=100)),
                ('code', models.CharField(blank=True, default='NEW_CUSTOMER', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OcrFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('upload', models.FileField(upload_to='ocr/%Y/%m/')),
                ('show', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_files', to='ums.Profile')),
            ],
        ),
    ]
